# Generated by Django 3.1 on 2020-10-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201018_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
