# Generated by Django 3.1 on 2020-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_report_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='money_choice',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=200),
        ),
    ]
