# Generated by Django 3.1 on 2020-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201020_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='money_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=200),
        ),
    ]
