# Generated by Django 3.1 on 2020-10-21 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_report_money_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('image', models.FileField(upload_to='')),
                ('amount', models.FloatField()),
                ('no_of_pices', models.IntegerField()),
                ('bought_from', models.CharField(max_length=600)),
                ('bought_date', models.DateField()),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
